CREATE TABLE IF NOT EXISTS Country (
	Id	INTEGER NOT NULL UNIQUE,
	Code	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY(Id)
);

INSERT INTO Country (Id, Code, "Name") VALUES (112, "BLR", "Belarus");

PRAGMA foreign_keys = 0;
ALTER TABLE Team ADD COLUMN CountryId INTEGER
            NOT NULL REFERENCES Country(Id) DEFAULT 112;
PRAGMA foreign_keys = 1;

UPDATE DbInfo SET Version = 1;